spring:
  application:
    name: cqrs-demo
  cloud:
    stream:
      bindings:
        input:
          destination: ex.stream.out2
          group: cart
        output:
          destination: ex.stream.out2


server:  
  port: ${PORT:8080}